### ISSUE TITLE
Import backup file to JUSTIFI - aggregate to existing user

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#157]
#39 implemented an importing approach to overwrite the current user data with the backup file content.
It would be better to add an option to aggregate  current user data with the data from the backup file. To do this,

- [x] Add a select list with overwrite and non-overwrite options
- [x] For non-overwrite option, the current user GUID/id will be used for backup file data to aggregate onto. The GUIDs for the data in backup file will need to be replaced with new GUIDs (except for the user data).

**Comment by ghost** [comment]
Using v0.0.1-alpha-c8b1299, I was able to export the database containing a test company, facility, and assessment, to a JSON file and then re-import it. After selecting the file to import, the "Import Data" modal now presents a new field "Import User ID" and a new input field "Overwrite Current User Data?" which is a select dropdown. I was able to import the contents of my file successfully using both options, and confirmed it behaves as expected by using the "My Portfolio" view. I believe the main features of the issue is implemented. However, there are some UI challenges presented by the feature. Two in particular:

1. Importing companies, facilities, and assessments with the same name as existing entities results in duplicate entity names in the database, and it is not possible to distinguish between the recently imported entity and one which existed in the database before import. This is confusing for the user, since they may have updated an entity prior to import and now can not easily distinguish which one is which. Potential solutions could be:
  - Add suffix to duplicated entity names, such as "My Company (Duplicated)" or "My Company (Import 8/9/2024 9:14:39AM)"
  - Update a "date created" or "date imported" field on import and make this field visible in the UI to distinguish between entities.
2. If a database is large and contains many entities which are duplicated then importing via merging may result in a polluted database with lots of duplicated entities. Consider allowing the user to select a subset of entities in the import / export modal.

I think it would be prudent to add a fix for (1) with this pull request.
Issue (2) could be spun out into a new / larger issue upgrading the import/export functionality.

**Comment by RLiNREL** [comment]
@jperrsau-at-nrel thanks for the comment.
For 1: Will implement a checker for the guid with existing entities in DB. If a match is found, add a (Duplicated) to the entity names from backup file.
Overall, the use case of exporting the database and importing it back is rare, this is not a major concern. If the user messes up with some entities and wants to "restore" using the importing features for those specific entities, we can address these with (2) and allow the user to select certain items to import.

**Comment by rmroot** [comment]
We have dates for created and modified on all db entries. I wouldn't put too much effort into check and adding "Duplicate" to same named objects. VERIFI/MEASUR allow same names for companies/facilities ect. and users are able to manage just fine.

**Comment by RLiNREL** [comment]
Thanks @rmroot for the input. I thought about the dates, but they don't get exposed on the current UI, like the dashboard. Do VERIFI/MESUR show the created/modified dates if a user wants to see more details about a particular entity? If there is a differentiator that can be exposed to the user, then adding a suffix is not necessary.

**Comment by rmroot** [comment]
They are not currently displayed anywhere no. That could be added as a new issue.

**Comment by RLiNREL** [comment]
Let's close this #157 and create a new issue for the duplicated entities imported from backup files #198. We will go from there. But generally, I think it is a big concern, but nice to have and let's put it in the ice-box. Thanks
