### ISSUE TITLE
Implement Strategic Goals data member

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#58]
Each company has strategic goals. For now, these will be added or "enabled" for a company, but they may also be attach to Processes or to NEBs in the future. We don't yet have a comprehensive list of strategic goals, but we can start with:

- Safety
- Maintaiance costs
- GHG emissions
- Productivity
- Quality

Each strategic goal requires a KPI, a description, and potentially a list of stakeholders / contacts who are relevant decision makers to this goal.

**Comment by jordanperr** [comment]
Reviewing v0.0.1-alpha-bae4b42

I have defined two new terms here:
- "Active KPI" - KPI which is currently in use by the project. Currently represented as a UI element in the lower half of the page.
- "Selected KPI" - Active KPI which is currently open, or being edited by the user.

The features requested in this issue are implemented, and also more. There is a list of KPIs and ability add custom KPIs. Inactive KPIs are listed towards the top of the page and clicking on them activates the KPI, moving it to the bottom of the page. Clicking on an active KPI expands it, showing details the user can fill in. Quantitative KPIs have three fields " Units" "Baseline use per year" and "cost per unit". Qualitative KPIs have no extra metadata at this time. The table works as expected and is reasonably intuitive, however, I think the UX team could review the page and streamline some of the actions. For example, there may not be a need to have KPIs expand and contract when de-selected. They could all simply be visible in a table.

Comments on Features:

- [x] There is not yet a "contact" or "stakeholder" data member for strategic goals. Given we now have a "Team Details" page, I think we can call this good for now and put this specific issue on the backlog: #76

Comments on UI:

- [x] Search function does not match "CO2e" without typing special characters (such as the subscript 2).
- [x] Adding KPIs by clicking them, and then having to scroll down to them, is awkward.
- [x] It is not obvious that the items in the upper list are "inactive" and the kpis in the bottom list are "active"
- [x] Clicking to expand an active KPI closes the other open KPI.
- [x] If you have more than one active KPI, selecting a different active KPI causes the browser window to scroll to an incorrect location, where the newly opened KPI is not completely visible.
- [ ] Navigating directly to the page "https://gray-tree-06c66911e.4.azurestaticapps.net/setup-wizard/company-kpi" without first initializing the setup wizard results in a blank page. I would prefer it redirect to the homepage in these cases. (Added a separate issue https://github.com/NREL/NEB-Tool/issues/77 )
- [x] When you delete an active "custom KPI" it is gone from the app, whereas when you delete a regular active KPI, it moves into the upper portion of the screen.

Actions:

I would suggest that the low-hanging fruit is fixed here (such as the search feature, the redirect). Then create a new ticket in the backlog for the more involved UI issues and reference it here before closing.

**Comment by ghost** [comment]
Re-reviewing with version v0.0.1-alpha-11d1dd2

Changes relevant to this issue: 
- Search feature has been fixed by removing subscripts from KPI text, and replacing them with names that are easier to type (such as "CO2"). The search seems to be case-insensitive, which is preferred. We may need to revisit this search in the future, but current implementation is perfect for now.
- The selection UI has been updated to a two-column layout, where selected KPIs on on the right, and you add them by clicking a plus button on the KPIs on the left. This UI makes much more sense to me, and you don't have to scroll as much.
- The KPI details screen has been moved to their own page. Upon clicking on an active KPI, a new page is created in the navigation bar and you are redirected to the page. This is better to me than the accordion, but I don't think it is completely solved yet. I've created a new [Zenhub issue #3](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/zh/3) to revisit this.
- There is a new warning modal upon deletion of KPIs, and they are destructive for both custom and built-in KPIs.


New issues identified:
- The "Energy Cost" KPI includes only one field, in units of "MMBtu" - even if you've selected other types of energy in the Company Details page. I've created a new [Zenhub Issue 4](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/zh/4) for this.
-
