### ISSUE TITLE
On Site Assessment First Pass

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#74]
Now that we have a pre-visit and on-site setup broken up in the wizard. The pre-assessment has been completed, we need to implement the onsite assessment page. This is the most important page that should be mobile friendly, be cognizant of that while building out this page but don't let it hold up development too much. Main focus is that we need to be able to complete this step to get through the entire process.

**Comment by jordanperr** [comment]
In v0.0.1-alpha-06d0278 - I am unable to enter the "On Site Assessment" portion of the wizard.

Steps to reproduce:
- Reset your database.
- From the homepage, click "Setup Wizard"
- Click "Pre-Visit Setup"
- In the modal, click "Confirm"
- From the hamburger menu, click "Setup Wizard"
- Click "Data Collection"
- In the company drop down, select "New Company" (NOT "Create New Company")
- In the facility drop down, select "New Facility" (NOT "Create New Faility")
- In the select visits drop down, select "May 29th" (although not sure where this date comes from, might be the current date).
- Click "Confirm"

Expected behavior: I am taken to the "On-Site wizard".
Observed behavior: I am taken to the "Setup Wizard" page.

**Comment by rmroot** [comment]
This was a good catch. The problem was that no assessments were added in the pre-visit. I've modified the data collection portion in the wizard to have a page that can add/delete assessments. Users will be brought to this page if they go to the data collection and don't have any assessments added in the pre-assessment portion.

Thanks for the good repro steps!

**Comment by ghost** [comment]
Confirmed this is now fixed. "On site assessment" has been renamed "Data collection" and contains two pages: Manage Assessments and Preliminary results. The "Manage Assessments" page allows you to create and delete your energy assessments, which then appear in the left menu. Each assessment's page then allows you to add projects under the assessment, and connect projects to nebs in a many-to-many relation. While of course there is more to do in this section, it is more than sufficient for a "first pass" at the on-site assessment.
