### ISSUE TITLE
Many to Many relationship between Projects and NEBs is confusing

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#88]
The many-to-many relationship between NEBs and Projects was confusing. Some suggestions include:

- Change the relationship to a one-to-many for Projects to Nebs in Wizard 2, and then allow the user to refine these relations at a later stage.
- Group the nebs by project, where duplicate nebs are functionally linked together (such that changes to a NEB in one project is reflected in the other project).

**Comment by rmroot** [comment]
Comment on PR: 

- Updated the UI for the relationship of NEBs to Energy opportunities
- Tied key performance metrics to the non energy benefits items
- Uses data from excel document with table of non energy benefits tied to KPI/KPMs
- Added tabs to the onsite assessment for "Details", "Energy Opportunities" and "NEBs". Users can add NEBs connected to energy opportunities or just straight to the assessment using the different tabs.
- The current NEB database is used but many of the metrics for calculating results are a work in progress

**Comment by rmroot** [comment]
New issues: 
#141
#140

**Comment by ghost** [comment]
Reviewing v0.0.1-alpha-c933213. This is an excellent approach and I think it's much less confusing than the previous version. NEBs can be added at both the Energy Opportunity and Assessment level, using a 1-many relation within each. The NEBs are grouped by energy opportunity, but instead of "functionally linking" the NEBs, we've decided to split the data into KPI (Baseline) and the NEB (NEB Impact). The user is unable to change the baseline values from the NEB directly, instead has to go back to relevant KPIs page in the Pre-Visit section to modify these values. When a value is changed, it is indeed updated across all Energy Opportunities. 

Really nice work on this one, @rmroot !

One rough spot for which I've created a new issue:

- New issue #150: The accordion-style tabs for "Energy Opportunities" within an assessment are confusing to me. Maybe I just don't like the accordion view, as it hides data from the user and makes it difficult to see all of your energy opportunities at once. I recommend we move away from the accordion in future versions.
